services:
  - type: web
    name: Integrador.II
    runtime: docker
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/GestionResiduos-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17